spring.application.name=serviceOKTA

# SAML Identity Provider Metadata
spring.security.saml2.relyingparty.registration.my-saml-app.assertingparty.metadata-uri=https://login.microsoftonline.com/70cd6baf-d633-49e5-ab08-2d0d6d4f4ca0/federationmetadata/2007-06/federationmetadata.xml?appid=75df76e9-214b-4feb-91d6-0c4dc7e29877
# SAML Single Logout (SLO)
spring.security.saml2.relyingparty.registration.my-saml-app.assertingparty.singlelogout.url=https://localhost:8080/slo-endpoint
spring.security.saml2.relyingparty.registration.my-saml-app.assertingparty.singlelogout.response-url=https://localhost:8080/logout

spring.security.saml2.relyingparty.registration.my-saml-app.entity-id=http://localhost:8080/saml2/service-provider-metadata/my-saml-app1

