spring.application.name=SpringBoot_Oauth2

#for Google
spring.security.oauth2.client.registration.google.client-id=1005540663041-hj0g6te6ivg8vuov11ivggn6enk6d3pc.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

#for Github
spring.security.oauth2.client.registration.github.client-id=Ov23liiN0cSJ8Tri1psf
spring.security.oauth2.client.registration.github.client-secret=264f3e3e6b99b8bab2004aafa3be1d593647e962

#for facebook
spring.security.oauth2.client.registration.facebook.client-id =605501278674794
spring.security.oauth2.client.registration.facebook.client-secret=274105104e85eae411e9fc9d51a8b69b




#for Azure 
spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=70cd6baf-d633-49e5-ab08-2d0d6d4f4ca0
spring.cloud.azure.active-directory.credential.client-id=2803cde0-a46e-4b34-8d59-e1dbea3b1e53
spring.cloud.azure.active-directory.credential.client-secret=PPL8Q~BAxKsI23sP7QIAGOkrifnMKp.zARdkZdyv

server.forward-headers-strategy=native