spring.application.name=SpringBoot_Security1
#spring.security.user.name=nitish
#spring.security.user.password=Nitish2003

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/SpringBoot_Security1
spring.datasource.username=root
spring.datasource.password=Root@2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

server.port=8084
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#eureka.instance.hostname=localhost
#eureka.instance.nonSecurePort=8084
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# SAML Identity Provider Metadata (Azure AD)
spring.security.saml2.relyingparty.registration.my-saml-app.assertingparty.metadata-uri=https://login.microsoftonline.com/70cd6baf-d633-49e5-ab08-2d0d6d4f4ca0/federationmetadata/2007-06/federationmetadata.xml?appid=1cea2cdd-d0e9-4c2b-adf9-eea6f30fbee3
# SAML Single Logout (SLO)
spring.security.saml2.relyingparty.registration.my-saml-app.assertingparty.singlelogout.url=https://login.microsoftonline.com/70cd6baf-d633-49e5-ab08-2d0d6d4f4ca0/saml2
spring.security.saml2.relyingparty.registration.my-saml-app.assertingparty.singlelogout.response-url=https://localhost:8084/logout

# Your Spring Boot application's entity ID
spring.security.saml2.relyingparty.registration.my-saml-app.entity-id=https://localhost:8084/saml2/service-provider-metadata/my-saml-app22

## Ensure SAML authentication requests are signed
#spring.security.saml2.relyingparty.registration.my-saml-app.authn-request-signed=true
